<?php

namespace CCK\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTermRepository extends EntityRepository
{
	/**
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function getNewTermID(){
		$sql = "
			SELECT * FROM SubTerm WHERE SubTerm.id = (SELECT MAX(SubTerm.id) FROM SubTerm)
		";
		$result = $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();

		return $result;
	}

	/**
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function getSubTermByCurriculumId($curriculum_id, $main_term, $term){
		$sql = "
				SELECT * FROM
						MainTerm
					INNER JOIN
						SubTerm ON (MainTerm.term_id = SubTerm.main_term_id
							AND MainTerm.delete_flag = false
							AND SubTerm.delete_flag = false)
					WHERE REPLACE_TAGS(SubTerm.sub_term) collate utf8_unicode_ci  = '" . $term . "'
						AND MainTerm.main_term = '". $main_term . "'
						AND MainTerm.curriculum_id = ". $curriculum_id;

		$result = $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();

		return $result;
	}
}
