<?php

namespace CCK\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends EntityRepository
{
	/**
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function getUploadList($cond = null){
		$sql = "
			SELECT
				Curriculum.name cur_name,
				Version.name ver_name,
				User.name user_name,
				Upload.file_name,
				Upload.create_date,
				Upload.contents
			FROM
				Upload
					INNER JOIN
				Version ON (Upload.version_id = Version.id)
					INNER JOIN
				Curriculum ON (Curriculum.id = Version.curriculum_id)
					INNER JOIN
				User ON (Upload.user_id = User.user_id)
			WHERE
				Curriculum.delete_flag = FALSE
				AND Version.delete_flag = FALSE
				AND Upload.delete_flag = FALSE";

		if($cond == "term"){
			$sql .= " AND Upload.contents is not NULL";
		}

		$sql .= " ORDER BY Upload.create_date DESC LIMIT 30";

		$result = $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();

		return $result;
	}
}
