<?php

namespace CCK\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VacantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacantRepository extends EntityRepository
{
	/**
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function getOccupiedYougoData($yougoid,$userid){
		$sql = "
			SELECT *
			FROM
				Vacant
			WHERE
				Vacant.term_id = ".$yougoid."
					AND
				Vacant.user_id != '".$userid."'
					AND
				Vacant.delete_flag = 0
		";

		$result = $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
		return $result;
	}
}
