<?php

namespace CCK\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
	public function getVersions($cur = null){
		if($cur != '0'){
			$qb = $this->createQueryBuilder('c')
			->select('c.name')
			->addSelect('c.id')
			->where('c.deleteFlag = :deleteFlag')
			->andWhere('c.curriculumId = :curriculum_id')
			->addOrderBy('c.id')
			->setParameters(array(
					'deleteFlag' => false,
					'curriculum_id' => $cur
			));
		}else{
			$qb = $this->createQueryBuilder('c')
			->select('c.name')
			->addSelect('c.id')
			->where('c.deleteFlag = :deleteFlag')
			->addOrderBy('c.id')
			->setParameters(array(
					'deleteFlag' => false
			));
		}

		return $qb->getQuery()->getResult();
	}
}
