<?php

namespace CCK\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
	public function getVersions($cur = null){
		$qb = $this->createQueryBuilder('c')
		->select('c.name')
		->addSelect('c.id')
		->where('c.deleteFlag = :deleteFlag')
		->andWhere('c.curriculumId = :curriculum_id')
		->addOrderBy('c.id')
		->setParameters(array(
				'deleteFlag' => false,
				'curriculum_id' => $cur
		));

		return $qb->getQuery()->getResult();
	}
}
